### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by rediattewolde** [appliedbinf/el_gato#15]
Dear El_gato developer

Thank you for developing el_gato.

Of 752,  5  samples gave  the following error. Would it be possible to fix the error or terminate the script with "failed" output ("standard out")

Many thanks

![image](https://github.com/appliedbinf/el_gato/assets/25207025/b21c46be-0785-4b5c-bc81-c38ef493ed5a)

**Comment by Alan-Collins** [comment]
Hi,

We have been working on some issues on the dev branch recently. One of the issues we fixed was producing an error like this. Would you mind trying the dev branch with these samples and letting me know if that fixes the issue?

Thanks,
Alan

**Comment by rediattewolde** [comment]
Hi Alan

I tried the  dev branch with the samples and the error is now fixed.
Thanks
Rediat
