### ISSUE TITLE
Database update

### ISSUE THREAD

**Issue by EricFournier3** [appliedbinf/el_gato#16]
Hi,

What is the frequency of your SBT database update?

Is there an option to execute this update locally on user side?

Thanks

Eric

**Comment by Alan-Collins** [comment]
Hi Eric,

We plan to update the database annually at a minimum and will be updating very soon along with a new release that makes several improvements. If you want access to the latest version, you can find that on the dev branch.

There is an option to provide your own database. You can specify the sbt sequences with `--sbt` or `-s` and can specify an MLST profile file with `--profile` or `-p`.

If you do provide your own database, note that the directory you provide must contain the following files:

| File                 | Description                                                                                                                                                             |
|----------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| all_loci.fasta       | fasta format sequence of all alleles for all loci                                                                                                                       |
| lpneumophila.txt     | MLST profile file (Unless you are providing it using `--profile` or `-p`                                                                                                                                                      |
| mompS_primer1.tab    | primers for use in assembly-based operation. You can get that file [here](https://github.com/appliedbinf/el_gato/blob/main/el_gato/db/mompS_primer1.tab)                |
| mompS_primer2.tab    | more primers for use in assembly-based operation. You can get that file [here](https://github.com/appliedbinf/el_gato/blob/main/el_gato/db/mompS_primer2.tab)           |
| ref_gene_regions.fna | Sequences used for read mapping in read-based operation. You can get that file [here](https://github.com/appliedbinf/el_gato/blob/main/el_gato/db/ref_gene_regions.fna) |

**Comment by EricFournier3** [comment]
Great,

thank you @Alan-Collins
