### ISSUE TITLE
1.20.0 to bioconda?

### ISSUE THREAD

**Issue by russellsmithies** [appliedbinf/el_gato#21]
Could someone please push 1.20.0 to bioconda?

thanx  :-)

**Comment by Alan-Collins** [comment]
Yes, we will have it up on Bioconda soon. The automatic release had some build issues (https://github.com/bioconda/bioconda-recipes/pull/51051) and I have not had time to diagnose and fix the issue yet.

**Comment by Alan-Collins** [comment]
1.20.1 is now live on bioconda.

Thanks!
