### ISSUE TITLE
isPcr check failing when running in a container due to grep -P

### ISSUE THREAD

**Issue by DarianHole** [appliedbinf/el_gato#22]
Hi,

The isPcr check `isPcr 2>&1 | head -1 | grep -Po "(?<=v )\S+"` is failing when running in the https://depot.galaxyproject.org/singularity/el_gato:1.20.1--py311h7e72e81_0 singularity container

From testing, the issue appears to be that the container doesn't support the `-P` perl-extended regex flag used. Are you able to adjust it to accommodate that restriction? I had `grep -o "v [0-9]\+x[0-9]\+" | sed "s/v //"` and that seems to have worked in its place but it isn't as elegant a statement

Thanks,
Darian

**Comment by Alan-Collins** [comment]
Hi Darian,

Thanks for raising this issue! it's hard to beat the elegance of PCRE lookarounds, but it seems the singularity container version of grep supports extended regex so I change the command to `isPcr 2>&1 | head -1 | grep -Eo "v \S+" | cut -d" " -f2` as that seemed simplest. We'll include this change in our next release.

Thanks!
Alan

**Comment by DarianHole** [comment]
Thanks Alan! That is very much appreciated
