### ISSUE TITLE
Output directory 'output2019_mlst' exists and overwrite is turned off. Exiting

### ISSUE THREAD

**Issue by tbazilegith** [appliedbinf/el_gato#3]
HI Alan,
I tried to run el-gato on two samples, using this command
for samp in $(cat samples.txt); do
    /home/myUser/el_gato/el_gato/el_gato.py --assembly ../assemblies/${samp}_assembly.fasta --out output2019_mlst
done

The run failed with this error:
Output directory 'output2019_mlst' exists and overwrite is turned off. Exiting
Any ideas?
Thanks!
TJ

**Comment by Alan-Collins** [comment]
Hi TJ,

 

[As I said here](https://github.com/appliedbinf/el_gato/issues/2#issuecomment-1572679836) el_gato wants you to provide a different output directory for each sample. It writes output files with the same filenames each run so you can't write outputs from multiple runs in the same directory

 

Alan

**Comment by tbazilegith** [comment]
Thanks! I caught the issue by adding the sample name as subdirectory of the output dir.
