### ISSUE TITLE
Lines repeated in the MLST report

### ISSUE THREAD

**Issue by tbazilegith** [appliedbinf/el_gato#4]
Hi Alan,
Why I am getting two lines for one sample in the file possible_mlsts.txt?

Sample	ST	flaA	pilE	asd	mip	mompS	proA	neuA_neuAH
JAX19001326_assembly	Novel ST*	30	60*	43*	61	15*	29*	233*
JAX19001326_assembly	Novel ST*	30	60*	43*	61	15*	29*	233*

Is that meaningful?
Thanks!
TJ

**Comment by Alan-Collins** [comment]
Please see the readme for details of what is included in output files. Two lines in that file means that for at least one locus, two alleles were identified. You can look at the identified_alleles.fna file to see the sequences of all identified alleles.

The issues section of GitHub it intended to be a place where people can report bugs or problems with code. Please do not open issues that can be answered by reading the documentation.

**Comment by tbazilegith** [comment]
?
