### ISSUE TITLE
Bioconda Release

### ISSUE THREAD

**Issue by rpetit3** [appliedbinf/el_gato#6]
Hello! 

You've pretty much done all the work to get this onto Bioconda, any interest in taking the next step and putting it on Bioconda?

I can handle the submission, would only need a proper release to build from.

Cheers,
Robert

**Comment by Alan-Collins** [comment]
Hi Robert,

We do intend to put el_gato on Bioconda. We have a few bug fixes and changes to finish and then will start the submission in the next week or so.

Thanks!

**Comment by rpetit3** [comment]
Feel free to loop me in when you do so!
